SEED: 7
N: 512
DT: 1.0
THREADS: 128
GPU_HEAP_SIZE_BYTES: 524288000
THRESHOLD: 2
CONTROL_VARIANCE:
  - 0.0872665    // 5 degrees in radians squared
  - 0.15**2      // 0.15 meters squared
MAX_LANDMARKS: 600
START_POSITION:
  - 0.0
  - 0.0
  - 0.0
sensor:
  RANGE: 35
  FOV: 2.199114857512855
  MISS_PROB: 0.05
  VARIANCE:
    - 0.0225
    - 0.0003046174197867086
  MAX_MEASUREMENTS: 50

